### ISSUE TITLE
Code review 1

### ISSUE THREAD

**Issue by tshemsedinov** [Nester44/Doodle-Jump#1]
- Magic number: https://github.com/Nester44/Doodle-Jump/blob/b6bcd267ee1942338bbc7406d0b046abfced2382/src/index.js#L68
- Try to reduce number of lines: https://github.com/Nester44/Doodle-Jump/blob/b6bcd267ee1942338bbc7406d0b046abfced2382/src/index.js#L111-L116
- Magic numbers: https://github.com/Nester44/Doodle-Jump/blob/b6bcd267ee1942338bbc7406d0b046abfced2382/src/index.js#L133-L134
- Use intermediate variables: https://github.com/Nester44/Doodle-Jump/blob/b6bcd267ee1942338bbc7406d0b046abfced2382/src/index.js#L184-L190
- Try to use collection instead of https://github.com/Nester44/Doodle-Jump/blob/b6bcd267ee1942338bbc7406d0b046abfced2382/src/index.js#L249-L255
- Here: https://github.com/Nester44/Doodle-Jump/blob/b6bcd267ee1942338bbc7406d0b046abfced2382/src/index.js#L269 it's better to do so: `if (this.isGameOver) return;`

**Comment by Nester44** [comment]
**Done**
But i refactored the **4th** point in a different way from the proposed.

I carefully considered your proposal and found it very interesting, concise and easy to implement. But besides this, I considered the switch-case option, and came to the conclusion that the implementation of this task through it has some (and, it seems to me, undeniable advantages):
1) The readability of the code will increase significantly, due to the fact that with such a matching pattern, we immediately see the matching of the pattern of the function
2) using the IDE we can also jump directly to the place where the function is declared
3) the constructor is not overloaded with parameters
4) no need to handle negative scenarios (when we try to access the key of our object, we get undefined)
5) extensibility of this approach

And I remade the **3rd** point with intermidiate variables, but there are still 4 stroke in the if statement.

**Comment by Nester44** [comment]
I have completely rework the project, added version 2.0.
https://github.com/Nester44/Doodle-Jump/tree/main/V2.0

In the Doodle Jump V2.0:
- redesign of web page
- completely redesigned character physics (character moves, accelerates and decelerates much smoother and more realistic);
- changed character control (doodler reacts to pressing the key, if you release the key, the doodler stops);
- added border teleportation (if the doodler goes beyond the left border, it appears from the right)ж
- implemented custom settings choosing, currently there are 5 changeble options:
  1. Gap between platforms
  2. Platform speed
  3. Platform width
  4. Jump height
  5. Hardmode
- implemented hardmode (platfroms move on the X axis between borders)
- added responsive game screen size algorithm (now game can be played with monitors with different size withoud discomfort)

Plans to add different types of platforms and a choice of skins
